name: Deploy Bot (experimental)

on:
  push:
    branches: [ experimental ]

jobs:
  deploy:

    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install QEMU Emulators for Architectures
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm/v7
          push: true
          tags: nederlandsdiscord/taalbot:experimental

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Run docker-compose on Remote Server
        uses: appleboy/ssh-action@master
        env:
          HOST: ${{ secrets.HOST_ADDRESS }}
          USERNAME: ${{ secrets.HOST_USERNAME }}
          KEY: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          PORT: ${{ secrets.HOST_SSH_PORT }}
          SCRIPT: |
            mkdir taalbot-deployment-experimental
            cd taalbot-deployment-experimental
            git clone https://github.com/NederlandsDiscord/Taalbot
            cd Taalbot
            git checkout experimental
            
            export TAALBOT_VERSION=experimental
            export DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN_EXPERIMENTAL }}

            docker-compose down
            docker image rm nederlandsdiscord/taalbot:experimental
            docker-compose up -d

            cd ../..
            rm -rf taalbot-deployment-experimental
